### ISSUE TITLE
Running danspeech with example code results in error

### ISSUE THREAD

**Issue by Shadesfear** [danspeech/danspeech#12]
Ran the example code from Usage page in documentation, this resulted in the follwing stack tree. The wav file i used was recorded with Deepin Voice Recorder

``` 
> python3 danspeechtest.py 
Using device: cpu
DanSpeech model updated to: DanSpeechPrimary
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/resources.py", line 205, in __enter__
    self.audio_reader = wave.open(self.filepath, "rb")
  File "/usr/lib/python3.7/wave.py", line 510, in open
    return Wave_read(f)
  File "/usr/lib/python3.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python3.7/wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "/usr/lib/python3.7/wave.py", line 269, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/resources.py", line 212, in __enter__
    self.audio_reader = aifc.open(self.filepath, "rb")
  File "/usr/lib/python3.7/aifc.py", line 917, in open
    return Aifc_read(f)
  File "/usr/lib/python3.7/aifc.py", line 352, in __init__
    self.initfp(file_object)
  File "/usr/lib/python3.7/aifc.py", line 316, in initfp
    raise Error('file does not start with FORM id')
aifc.Error: file does not start with FORM id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "danspeechtest.py", line 12, in <module>
    audio = load_audio(path="/home/chris/Music/Recording/record.wav")
  File "/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/resources.py", line 36, in load_audio
    with SpeechFile(filepath=path) as source:
  File "/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/resources.py", line 241, in __enter__
    ], stdin=subprocess.PIPE, stdout=subprocess.PIPE, startupinfo=startup_info)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/flac-linux-x86_64': '/home/chris/.local/lib/python3.7/site-packages/danspeech/audio/flac-linux-x86_64'
```

**Comment by Rasmusafj** [comment]
Thanks for reporting the error. 

Judging from the stack trace, I think the error occurs since DanSpeech is unable to read the audio format of the .wav file. 

Can you provide a link to the file or a different file (perhaps silent recording) recorded using your setup of Deepin Voice Recorder? Then I might be able to patch DanSpeech to support the specific type of .wav you are using. 

If not, then try converting the .wav to PCM signed 16-bit little endian format using e.g. ffmpeg and it should work.

Let me know how it goes. :)

**Comment by Rasmusafj** [comment]
Closing due to innactivity.
