### ISSUE TITLE
Integer division error in Python3.6 error in danspeech

### ISSUE THREAD

**Issue by fnielsen** [danspeech/danspeech#18]
An integer division error appear for Python3.6

```
[27/Apr/2021 09:59:01] "POST /preprocess_audio/ HTTP/1.1" 200 17
Internal Server Error: /transcribe/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<path>/danspeechdemo/danspeechdemo/demo/views.py", line 146, in transcribe
    transcription = recognizer.recognize(audio, show_all=False)
  File "/usr/local/lib/python3.6/dist-packages/danspeech/Recognizer.py", line 95, in recognize
    return self.danspeech_recognizer.transcribe(audio_data, show_all=show_all)
  File "/usr/local/lib/python3.6/dist-packages/danspeech/DanSpeechRecognizer.py", line 218, in transcribe
    out, output_sizes = self.model(recording, input_sizes)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/danspeech/deepspeech/model.py", line 498, in forward
    output_lengths = self.get_seq_lens(lengths)
  File "/usr/local/lib/python3.6/dist-packages/danspeech/deepspeech/model.py", line 550, in get_seq_lens
    seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) / m.stride[1] + 1)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
[27/Apr/2021 09:59:02] "POST /transcribe/ HTTP/1.1" 500 96622
```

**Comment by fnielsen** [comment]
This has already been fixed with https://github.com/danspeech/danspeech/commit/ae334a67d44480e8d92513faa620ae2f9fe61539 However, the pip version fails.

**Comment by Rasmusafj** [comment]
Updated pip version to include commit ae334a6 :)

**Comment by Rasmusafj** [comment]
We have some newer, faster and better models based on the wav2vec2 architecture. They are not open sourced yet. Let me know if you want access to these @fnielsen before we officially open source them.

**Comment by s3n-r2k** [comment]
Hey @Rasmusafj are the new, faster and better models finetuned on a multilingual pretrained wav2vec2 model or have you created your own pretrained danish wav2vec2 model? In either case, that sounds pretty 😎

**Comment by Rasmusafj** [comment]
@SimonRask-Code Its purely danish and not multilingual. The pre-trained multilingual model is quite big (and thus less optimal in our production setting), hence we use the base wav2vec2 architecture instead. 

We've done the pre-training with 1200hours of data and fine-tuning with approx 4-500 hours of data. :)

**Comment by fnielsen** [comment]
Thanks for the information about the new models. I will let you now if I need them. What are the 1.200 hours? Folketinget? NST? There is the sprogteknologi.dk effort to create more data, possibly in specialized domains.
